# Generated by Django 5.2.5 on 2025-09-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('newsletter', models.BooleanField(default=False, verbose_name="S'abonner à la newsletter")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_en', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_fr', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_es', models.TextField(blank=True, max_length=200, null=True)),
                ('summary_ru', models.TextField(blank=True, max_length=200, null=True)),
                ('posted_as', models.CharField(choices=[('News', 'News'), ('Event', 'Event')], max_length=10)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Abonné à la newsletter',
                'verbose_name_plural': 'Abonnés à la newsletter',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, unique=True)),
                ('is_current_session', models.BooleanField(blank=True, default=False, null=True)),
                ('next_session_begins', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Étiquette')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Diapositive',
                'verbose_name_plural': 'Diapositives',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('value', models.PositiveIntegerField(verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Valeur de statistique',
                'verbose_name_plural': 'Valeurs de statistiques',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('content', models.TextField(max_length=500, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name="Photo de l'auteur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('is_current_semester', models.BooleanField(blank=True, default=False, null=True)),
                ('next_semester_begins', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('primary_cta', models.CharField(blank=True, max_length=100, verbose_name="Appel à l'action principal")),
                ('primary_link', models.CharField(blank=True, max_length=200, verbose_name='Lien principal')),
                ('secondary_cta', models.CharField(blank=True, max_length=100, verbose_name="Appel à l'action secondaire")),
                ('secondary_link', models.CharField(blank=True, max_length=200, verbose_name='Lien secondaire')),
                ('secondary_icon', models.CharField(blank=True, max_length=50, verbose_name='Icône secondaire')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.slide', verbose_name='Slide')),
            ],
            options={
                'verbose_name': 'Image du carrousel',
                'verbose_name_plural': 'Images du carrousel',
                'ordering': ['order'],
            },
        ),
    ]
