# Generated by Django 5.2.5 on 2025-09-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='level',
            field=models.CharField(blank=True, choices=[('Maternelle', 'Maternelle'), ('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], max_length=20, null=True, verbose_name='Niveau scolaire'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
