# Generated by Django 5.2.5 on 2025-09-06 10:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_parent_student'),
        ('core', '0002_contactmessage_level_contactmessage_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-featured', 'order', '-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'enfant"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Témoignage en vedette'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de 'utile'"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.parent', verbose_name='Parent concerné'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5 étoiles)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student', verbose_name='Élève concerné'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='subject_taught',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matière enseignée'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_type',
            field=models.CharField(choices=[('student', 'Élève'), ('parent', 'Parent'), ('teacher', 'Enseignant'), ('other', 'Autre')], default='student', max_length=10, verbose_name='Type de témoignage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
