# Generated by Django 5.2.5 on 2025-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testimonial_options_testimonial_child_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('activity', models.CharField(max_length=255, verbose_name='Activité')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Événement académique',
                'verbose_name_plural': 'Événements académiques',
                'ordering': ['date'],
            },
        ),
    ]
