# Generated by Django 5.2.5 on 2025-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_successrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Source'),
        ),
    ]
