# Generated by Django 5.2.6 on 2025-09-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_newsandevents_summary_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='summary_af',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ar',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ar_dz',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ast',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_az',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_be',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_bg',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_bn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_br',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_bs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ca',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ckb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_cs',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_cy',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_da',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_de',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_dsb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_el',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_en_au',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_en_gb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_eo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es_ar',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es_co',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es_mx',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es_ni',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_es_ve',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_et',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_eu',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_fa',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_fi',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_fy',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ga',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_gd',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_gl',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_he',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hi',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hsb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hu',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_hy',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ia',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ig',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ind',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_io',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_is',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_it',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ja',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ka',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_kab',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_kk',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_km',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_kn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ko',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ky',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_lb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_lt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_lv',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_mk',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ml',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_mn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_mr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ms',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_my',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_nb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ne',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_nl',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_nn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_os',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_pa',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_pl',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_pt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_pt_br',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ro',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ru',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sk',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sl',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sq',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sr_latn',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sv',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_sw',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ta',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_te',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_tg',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_th',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_tk',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_tr',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_tt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_udm',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ug',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_uk',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_ur',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_uz',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_vi',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_zh_hans',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='summary_zh_hant',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ckb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='title_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
