# Generated by Django 5.2.5 on 2025-09-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.CharField(blank=True, choices=[('Père', 'Père'), ('Mère', 'Mère'), ('Frère', 'Frère'), ('Sœur', 'Sœur'), ('Grand-mère', 'Grand-mère'), ('Grand-père', 'Grand-père'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primaire'), ('Secondary', 'Secondaire'), ('High', 'Lycée')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
