# Generated by Django 5.2.5 on 2025-09-07 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('academic_admin', 'Admin Académique'), ('secretary', 'Secrétaire'), ('finance', 'Comptable')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Administrateur',
                'verbose_name_plural': 'Rôles Administrateurs',
            },
        ),
    ]
