# Generated by Django 5.2.5 on 2025-09-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
    ]
